### PR TITLE
chore: workspace add example

### PR DESCRIPTION
**Pull request by Sunny-117**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### CODE REVIEW

**Comment by liuyib** [comment]
Why add example dir to the workspace?  @Sunny-117

**Comment by liuyib** [comment]
@crazylxr  @miracles1919  这个改动有必要吗？我怎么感觉没必要啊

**Comment by crazylxr** [comment]
没看明白是为了啥 ，目的是啥呢？@Sunny-117

**Comment by crazylxr** [comment]
先 close 了

**Pull request closed without merging**
