### PR TITLE
fix: 修复useInViewport的rootMargin值无法使用组件state更新

### LINKED ISSUE #1979: useInViewport的rootMargin值无法使用组件state更新
```
const [margin, setMargin] = useState('50px')
const [inViewport] = useInViewport(() => document.getElementById('box'), {
  rootMargin: margin
})
```
以上写法，不论如何设置**setMargin**，**rootMargin**的值将永远等于**50px**

### PR DESCRIPTION
**Pull request by captain1023**
fix rootMargin does not update when using setState

[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix bug #1979|
| 🇨🇳 Chinese | fix bug #1979|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by hchlq** [comment]
commit 的信息尽量语义化一点~

**Comment by captain1023** [comment]
> commit 的信息尽量语义化一点~

**Comment by captain1023** [comment]
> commit 的信息尽量语义化一点~

好的好的

**Review by li-jia-nan — APPROVED** [review]

**Comment by li-jia-nan** [comment]
threshold 是不是也可以作为依赖项监听一下？

**Comment by captain1023** [comment]
> threshold 是不是也可以作为依赖项监听一下？

我觉得大佬说的对😂

**Comment by miracles1919** [comment]
test 补一下吧 ~

**Comment by captain1023** [comment]
> test 补一下吧 ~

umm 因为这个要用react setState去设置margin,去改变rootMargin验证效果. 所以Test怎么写目前没什么思路. 可以麻烦大佬们提供个思路或者类似的test案例吗 🙏🙏🙏

**Review by crazylxr — APPROVED** [review]

**Pull request merged**
