### PR TITLE
fix: use memoized fn in useTimeout

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: use memoized fn in useTimeout |
| 🇨🇳 Chinese | fix: 修复了打开 react devtools 时 useTimeout 不工作的问题 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by liuyib** [comment]
useRafTimeout、useRafInterval 中也有类似的用法，是不是也需要测下？然后一起改了？ @li-jia-nan

**Comment by li-jia-nan** [comment]
我的建议是先把两个定时器改了，其它的有了 issue 再说，毕竟这个只在 react devtool 中才会出现，影响范围不是很大

**Comment by liuyib** [comment]
> 我的建议是先把两个定时器改了，其它的有了 issue 再说，毕竟这个只在 react devtool 中才会出现，影响范围不是很大

可以，我先记录下来，优先级降低，有空了测一测

**Review by liuyib — APPROVED** [review]

**Comment by liuyib** [comment]
@crazylxr  ready for review

**Review by crazylxr — APPROVED** [review]

**Pull request merged**
