### PR TITLE
fix: add Number.isNaN()

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | fix: add Number.isNaN() |
| 🇨🇳 Chinese |          - |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hchlq** [comment]
不建议这么做，为啥要在 isNumber 中去判断 NaN 呢，本身 NaN 就是 number 类型

**Comment by hchlq** [comment]
如果有使用到排除 NaN 的场景单独去判断处理就好了，这样做可能会导致使用的人没有注意到 isNumber 是排除了 NaN 的情况

**Comment by li-jia-nan** [comment]
我的想法是 NaN 不能作为 number，因为 number 类型的值在业务中会被用来计算，但是你说的也有道理，如果存在争议的话就先保持现有逻辑吧，我先 close 了

**Comment by liuyib** [comment]
可以像 lodash 那样，保留 `isNumber` 和 `isFinite`，其中 `isNumber` 包括 `Infinity/-Infinity/NaN`，`isFinite` 不包括

https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L12003

image

**Pull request closed without merging**
