### PR TITLE
fix(useInfiniteScroll): 修复 reload 时未先重置数据问题

### PR DESCRIPTION
**Pull request by dobble11**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by brickspert** [comment]
感谢贡献，✿✿ヽ(°▽°)ノ✿

我理解这是一个功能，不是一个 bug。

如果需要 reload 时页面不展示数据，可以通过 `loading` 来判断数据是否展示。

Thanks for contribution, ✿✿ヽ(°▽°)ノ✿

I understand this is a feature, not a bug.

If you does not display data when reload, you can use `loading` to determine whether the data is displayed.

**Comment by dobble11** [comment]
loading 没法区分是否是加载第一页数据，现在情况会导致列表组件 reload 时 无法看到 loading 组件，因为数据没被清空，被渲染在视窗下面

**Comment by dobble11** [comment]
v2 版本是清除了的

**Comment by brickspert** [comment]
> loading 没法区分是否是加载第一页数据，现在情况会导致列表组件 reload 时 无法看到 loading 组件，因为数据没被清空，被渲染在视窗下面

`loading=true` 一定是在加载第一页。
`loadingMore=true` 一定在加载非第一页。

**Comment by dobble11** [comment]
> 

ok

**Pull request closed without merging**
