### PR TITLE
feat: rename useControlledValue to useControllableValue

### PR DESCRIPTION
**Pull request by brickspert**

### CODE REVIEW

**Review by awmleer — APPROVED** [review]

**Review by ttys026 — APPROVED** [review]

**Comment by ttys026** [comment]
will that be a break change though?

**Comment by brickspert** [comment]
> will that be a break change though?

won't, because you can use `useControlledValue` as usual.

**Comment by awmleer** [comment]
May we can give the old `useControlledValue` function a deprecation warning?

For example:

```jsx
import useControllableValue from './useControllableValue';

const useControlledValue: typeof useControllableValue = function(...args) {
  console.warn('useControlledValue is deprecated and will be removed in the next major version. Please use useControllableValue instead.');
  useControllableValue(...args);
}
```

**Comment by brickspert** [comment]
> May we can give the old `useControlledValue` function a deprecation warning?
> 
> For example:
> 
> ```js-jsx
> import useControllableValue from './useControllableValue';
> 
> const useControlledValue: typeof useControllableValue = function(...args) {
>   console.warn('useControlledValue is deprecated and will be removed in the next major version. Please use useControllableValue instead.');
>   useControllableValue(...args);
> }
> ```

it's ok. you are so rigorous~ give you a flower ❀~

**Pull request merged**
