### PR TITLE
refactor: replace lodash/isEqual with react-fast-compare

### PR DESCRIPTION
**Pull request by guoyunhe**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

react-fast-compare 提供了与 lodash/isEqual 相同的能力，但是体积更小，性能快了数倍。

image

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by liuyib — APPROVED** [review]

**Comment by liuyib** [comment]
@li-jia-nan @hchlq @miracles1919 @crazylxr 
这个有必要替换吗？性能是提高了，但是不清楚会不会有潜在的问题，没用过这个库

**Comment by li-jia-nan** [comment]
> @li-jia-nan @hchlq @miracles1919 @crazylxr 这个有必要替换吗？性能是提高了，但是不清楚会不会有潜在的问题，没用过这个库

我也没用过这个

**Comment by crazylxr** [comment]
v4 再换吧，先 hold 一下

**Comment by guoyunhe** [comment]
@liuyib antd-mobile 已经换了，目前没有发现问题 https://github.com/ant-design/ant-design-mobile/blob/master/package.json#L33

**Comment by crazylxr** [comment]
那就整

**Pull request merged**
