### PR TITLE
feat(useInfiniteScroll): support scroll to top

### PR DESCRIPTION
**Pull request by jaluik**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

In many scenarios, users need to load more content when they scroll up, especially in chat applications and feeds. The current `useInfiniteScroll` hook in `ahooks` only supports loading more when scrolling down. To meet this requirement, I have extended `useInfiniteScroll` to support upwards infinite scrolling.

**Solution:**
- Added an option `direction: top` to `useInfiniteScroll` to enable upward scrolling.
- Modified the internal logic to handle upward scroll events and load more data accordingly.
- Ensured backward compatibility with existing downward scrolling functionality.

### 📝 Changelog

| Language   | Changelog                                   |
| ---------- | ------------------------------------------- |
| 🇺🇸 English | Added `direction` option to `useInfiniteScroll` hook to enable upward scrolling. |
| 🇨🇳 Chinese | 给 `useInfiniteScroll` 增加了`direction`选项提供向上滚动加载的支持。      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by hchlq** [comment]
补一下单侧哈

**Comment by jaluik** [comment]
> 补一下单侧哈

ok

**Comment by jaluik** [comment]
> 补一下单侧哈

单测加好了  @hchlq

**Comment by jaluik** [comment]
@liuyib @hchlq  有人review一下代码吗

**Pull request merged**
