### PR TITLE
docs: 更通俗些的滚动无限加载 demo

### PR DESCRIPTION
**Pull request by shaunhurryup**
### 🤔 This is a ...

- [x] Demo update

### 💡 Background and solution

滚动无限加载给的 demo 有点难理解，不太直观，提供了一种更直白的方式。

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by liuyib** [comment]
> [CLA assistant check](https://cla-assistant.io/alibaba/hooks?pullRequest=2072) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/hooks?pullRequest=2072) before we can accept your contribution.
> 
> **xincan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/hooks?pullRequest=2072) it.

@xincan1949  please sign the CLA

**Comment by shaunhurryup** [comment]
改了个邮箱，辛苦跟进下 PR 流程~

**Comment by liuyib** [comment]
@xincan1949  重新格式化一下代码，你把原来的格式都改了，引入了很多无关的改动，diff 看起来比较费劲。或者你把提的 PR 的选项 “Allow edits from maintainers” 勾上，这样我就可以帮你改了

**Comment by liuyib** [comment]
@xincan1949   上面的代码格式化不用改了，这个 PR 的改动和第三个 Demo “滚动自动加载”重复了，先关了，有问题的话请再接着评论

**Pull request closed without merging**
