### PR TITLE
chore: code format for prettier & type definition optimization

### PR DESCRIPTION
**Pull request by li-jia-nan**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | chore: code format for prettier & type definition optimization |
| 🇨🇳 Chinese | chore: 代码格式化 & 类型定义优化 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by miracles1919** [comment]
改动太多了... 拆一下 PR 吧

**Comment by li-jia-nan** [comment]
> 改动太多了... 拆一下 PR 吧

怎么拆呢大佬？每个hook要单独提一个吗？

**Comment by miracles1919** [comment]
分个类？ format 的，type 调整的， ...etc

**Comment by li-jia-nan** [comment]
> 分个类？ format 的，type 调整的， ...etc

回滚了，这里只做 format 格式化的改动，后面 type 优化我再单独提一个pr

**Pull request closed without merging**
