### PR TITLE
fix: 修復虛擬DOM可以被代理的bug

### PR DESCRIPTION
**Pull request by Accepted1**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by crazylxr** [comment]
这个 bug 能详细描述一下什么情况吗？

**Comment by hchlq** [comment]
好像是 useReactive 传入了 JSX 对象，感觉不是很有必要捏，后面会打算去掉这个 hook~

**Comment by Accepted1** [comment]
> useReactive 传入了 JSX 对象，會導致不必要的bug產生

**Comment by crazylxr** [comment]
我们讨论了下，想不到什么情况会传虚拟dom 进去，如果要考虑这个，需要考虑的东西就太多了，暂时不加

**Pull request closed without merging**
