### PR TITLE
fix typo useRquest -> useRequest

### PR DESCRIPTION
**Pull request by muescha**

### CODE REVIEW

**Comment by muescha** [comment]
i don't sign an CLA where i can not read the chinese parts (which are also part of this "contract")

**Comment by brickspert** [comment]
> i don't sign an CLA where i can not read the chinese parts (which are also part of this "contract")

You just need to click the button at the bottom

image

**Review by brickspert — APPROVED** [review]
LGTM

**Comment by muescha** [comment]
> > i don't sign an CLA where i can not read the chinese parts (which are also part of this "contract")
> 
> You just need to click the button at the bottom
> 
> image

yes - but i need to understand what i am signing, and there are parts of this agreement which i give my sign which i not understand because it is in a different language as english.

**Pull request merged**
