### PR TITLE
perf: useEventEmitte with useCreation

### PR DESCRIPTION
**Pull request by it-beige**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### useEventEmitter通过useCreation初始化EventEmitter类进行避免不必要构建

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ☑️] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by liuyib** [comment]
> 避免不必要构建

这点指的是？ 旧的代码只会在首次渲染时执行 `new EventEmitter()`，替换成这个 PR 中新的代码后，只能说效果等价，基本没有更进一步性能优化。

**Comment by kongmoumou** [comment]
没有优化，甚至引入了更多运算开销...

**Comment by liuyib** [comment]
> 没有优化，甚至引入了更多运算开销...

+1

**Comment by it-beige** [comment]
抱歉, 对于原理理解不够, 我关闭这个pr吧

**Comment by liuyib** [comment]
> 抱歉, 对于原理理解不够, 我关闭这个pr吧

没事的，想参与贡献还有很多其他机会，issue 区有很多问题待解决呢，以后多多参与哦~

**Pull request closed without merging**
