### PR TITLE
feat: useMap use object as initialValue

### PR DESCRIPTION
**Pull request by c0dedance**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | useMap use object as initialValue |
| 🇨🇳 Chinese | useMap可使用object进行初始化 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by crazylxr** [comment]
这个改动的动机是啥？

**Comment by SignDawn** [comment]
对象转 map ? 这自己做会不会更好？

**Comment by miracles1919** [comment]
感觉收益不大，而且处理 object 的操作，在 hook 外部只需要一次；而放在 hook 里，每次 init、reset 的时候，都要执行一次

**Comment by crazylxr** [comment]
感谢 pr，感觉这收益不太大，先 close 了

**Pull request closed without merging**
