### PR TITLE
chore: usePrevious中的普通赋值改为解构赋值

### PR DESCRIPTION
**Pull request by buzuosheng**
[[中文版模板 / Chinese template](https://github.com/alibaba/hooks/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Review by brickspert — COMMENTED** [review]
代码可读性变差了，不建议这样修改哈。

**Comment by buzuosheng** [comment]
> 代码可读性变差了，不建议这样修改哈。

在交换值的场景中，我觉得使用解构赋值更加方便，而且避免了赋值前后顺序可能会出现的问题

**Comment by crazylxr** [comment]
> 在交换值的场景中，我觉得使用解构赋值更加方便，而且避免了赋值前后顺序可能会出现的问题

避免了赋值前后顺序可能会出现的问题 是指什么问题？

**Comment by crazylxr** [comment]
这个 pr 暂时先关了哈

**Pull request closed without merging**
